#!/bin/bash

# Global settings
set -o pipefail
SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "${SCRIPT_PATH}")

. "${SCRIPT_DIR}/exec_functions"

# Support functions

function usage() {
  cat <<_EOF_
commands:
  next_env
  env_promote
  ansible-playbook
_EOF_
}

COMMAND="$1"
shift

case "$COMMAND" in
  run_dir_dockerfile)
    if ! run_dir_dockerfile "$@" ; then
      echo "Failed to execute run_dir_dockerfile"
      exit 1
    fi
    ;;
  run_dirs_docker)
    if ! run_dirs_docker "$@" ; then
      echo "Failed to execute run_dirs_docker"
      exit 1
    fi
    ;;
  github_release)
    if ! github_release "$@" ; then
      echo "Failed to perform github_release"
      exit 1
    fi
    ;;
  next_env)
    if ! next_env "$@" ; then
      echo "Failed to perform next_env"
      exit 1
    fi
    ;;
  azd_env_promote)
    if ! azd_env_promote "$@" ; then
      echo "Failed to perform env_promote"
      exit 1
    fi
    ;;
  ansible-playbook)
    if ! ansible_playbook "$@" ; then
      echo "Failed to run ansible_playbook"
      exit 1
    fi
    ;;
  ansible-setup)
    if ! ansible_setup "$@" ; then
      echo "Failed to run ansible_setup"
      exit 1
    fi
    ;;
  ansible_playbook)
    if ! ansible_playbook "$@" ; then
      echo "Failed to run ansible_playbook"
      exit 1
    fi
    ;;
  ansible_setup)
    if ! ansible_setup "$@" ; then
      echo "Failed to run ansible_setup"
      exit 1
    fi
    ;;
  ""|"help")
    usage
    exit 0
    ;;
  *)
    echo "Unknown command: $COMMAND"
    exit 1
    ;;
esac

exit 0
