---

name: latest-build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  latest:
    name: "latest-build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
